//import org.jetbrains.kotlin.config.KotlinCompilerVersion

/*
 * This file was generated by the Gradle "init" task.
 */


//val kotlinVersion = "1.1.1"

plugins {
    id("java")
    kotlin("jvm") version "1.3.70"
    id("maven-publish")
}

repositories {
    mavenLocal()
    maven(
        "https://repo.maven.apache.org/maven2"
    )
}

dependencies {
    implementation(kotlin("stdlib"))
    implementation("org.json:json:20150729")
    testImplementation(kotlin("test"))
    testImplementation(kotlin("reflect"))
    testImplementation("org.jetbrains.spek:spek-api:1.1.5")
    //testImplementation(kotlin("test", version = "1.1.1"))
    //testImplementation(kotlin("reflect", version = "1.1.1"))
}

group = "com.github.kliberty"
version = "1.0.0"
description = "khttp"
//sourceCompatibility = JavaVersion.VERSION_1_8
val sourceCompatibility = "1.8"

tasks.register<Jar>("sourcesJar") {
    //classifier = "sources"
    from(sourceSets.main.get().allJava)
    archiveClassifier.set("sources")
}

//publishing {
//    publications {
//        maven(MavenPublication) {
//            from(components.java)
//            artifact(sourcesJar)
//        }
//    }
//}

//tasks.withType(JavaCompile) {
//    options.encoding = "UTF-8"
//}
